version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lightning
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '15432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
